import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const OUTPUT_PATH = path.resolve('esa/env.generated.js');
const ESA_ENV_KEYS = [
  'QWEN_BASE_URL',
  'QWEN_API_KEY',
  'QWEN_MODEL',
  'QWEN_TIMEOUT',
  'DASHSCOPE_BASE_URL',
  'DASHSCOPE_API_KEY',
  'DASHSCOPE_MODEL',
  'DASHSCOPE_TIMEOUT',
  'CORS_ORIGIN'
];

export function collectEsaEnv(env = process.env) {
  return Object.fromEntries(
    ESA_ENV_KEYS
      .map((key) => [key, String(env[key] || '').trim()])
      .filter(([, value]) => value)
  );
}

export function buildGeneratedEsaEnvModule(env = process.env) {
  const values = collectEsaEnv(env);
  return `// Generated by scripts/generate-esa-env.js during ESA Pages build.
// Do not commit this file. It may contain server-side API credentials.
export default ${JSON.stringify(values, null, 2)};
`;
}

export function writeGeneratedEsaEnvModule(outputPath = OUTPUT_PATH, env = process.env) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, buildGeneratedEsaEnvModule(env), 'utf8');

  return {
    outputPath,
    entryCount: Object.keys(collectEsaEnv(env)).length
  };
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const result = writeGeneratedEsaEnvModule();
  console.log(`Generated ${result.outputPath} with ${result.entryCount} ESA env entries.`);
}
